// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestProject.Infrastructure;

namespace TestProject.Infrastructure.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20180927131449_many2")]
    partial class many2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestProject.Contracts.Entities.Catalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CatalogDescription");

                    b.Property<string>("CatalogName");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDateUtc");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDateUtc");

                    b.HasKey("Id");

                    b.ToTable("Catalog");
                });

            modelBuilder.Entity("TestProject.Contracts.Entities.CatalogItems", b =>
                {
                    b.Property<int>("ProductId");

                    b.Property<int>("CatalogId");

                    b.HasKey("ProductId", "CatalogId");

                    b.HasAlternateKey("CatalogId", "ProductId");

                    b.ToTable("CatalogItems");
                });

            modelBuilder.Entity("TestProject.Contracts.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("BasePrice");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDateUtc");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDateUtc");

                    b.Property<string>("ProductDescription");

                    b.Property<string>("ProductName");

                    b.HasKey("Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("TestProject.Contracts.Entities.CatalogItems", b =>
                {
                    b.HasOne("TestProject.Contracts.Entities.Catalog", "Catalog")
                        .WithMany("CatalogItems")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TestProject.Contracts.Entities.Product", "Product")
                        .WithMany("CatalogItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
